# base workload
CPU_H = 20
TOTAL_READS = 3000

# caching
CACHE_SKEW = 1.2
FIRST_READ_FROM_S3 = True

# materialization
SPOOLING_FRACTION = 0.5
SPOOLING_SKEW = 1.3
SPOOLING_READ_SUM = TOTAL_READS * SPOOLING_FRACTION
